### ISSUE TITLE
Landing Edits, March 7-8, 2019

### ISSUE THREAD

**Issue by cstiens** [digiresilience/landing#13]
![cdr_p2-intv1](https://user-images.githubusercontent.com/1434597/54004630-e8f7ff00-411b-11e9-9c0a-481da8a94797.png)

![cdr_p2-intv1-markup](https://user-images.githubusercontent.com/1434597/54004447-2c9e3900-411b-11e9-9a1a-f1ead12d71eb.png)

Below is the text for the site. I've also included a text file.

> Building resilient systems to keep civil society safe online
> 
> Our work protects civil society and empowers activists to regain civic space.
> 
> We believe digital security is a collective effort. We work with partners to bolster the digital strength and wellness of every individual within a community.
> 
> We aim to not only ensure timely and effective responses for our communities, but to reduce their need for emergency response in the first place.
> 
> Strengthen the digital wellness of your community with CDR.
> 
> Contact us to learn more about a tailored plan for your organization.
> 
> Tell me more

[CDR_p2_intv1-text.txt](https://github.com/digiresilience/landing/files/2944225/CDR_p2_intv1-text.txt)

[CDR_p2-intv1@1x.svg.zip](https://github.com/digiresilience/landing/files/2944227/CDR_p2-intv1%401x.svg.zip)

**Comment by cstiens** [comment]
@redaranj Hello! I've added specs, text and an .svg file of the design. Let me know if there's anything else you need!

**Comment by redaranj** [comment]
@csteins The updates are ready for you to take a look when you have a few minutes. We don't really have a staging server for this site so I'll push it to production when you're available and we'll update it quickly if there's anything that needs work.

**Comment by cstiens** [comment]
Thanks @redaranj! Where can I have a look?

**Comment by redaranj** [comment]
@cstiens It's up on https://digiresilience.org/ as of a minute ago.

**Comment by cstiens** [comment]
@redaranj Thanks! I've attached screenshots of what I see below.

Here are the changes that need to be made:
- [ ] I think the issue of the graphic overlapping the text is pretty clear. We need that to be fixed. 

- [ ] The font sizes / proportions need to be set as stated in the spec. It's really important to maintain the hierarchy in the design.

- [ ] We need padding on both sides of the text in the second section under 'Our work protects...' See the mockups.

- [ ] The 'Strengthen the digital wellness ...' section should be center aligned.

- [ ] The button within that section isn't rendering properly. It should be a pill style button with an orange background as shown in the design.

- [ ] The background of the 'Strengthen the digital wellness ...' section should be the gray and 'meet the team' white. See mockup.


<img width="1097" alt="screen shot 2019-03-08 at 9 01 45 am" src="https://user-images.githubusercontent.com/1434597/54036343-07dcac80-4181-11e9-9226-b07d4764b4be.png">

<img width="962" alt="screen shot 2019-03-08 at 9 04 02 am" src="https://user-images.githubusercontent.com/1434597/54036392-25117b00-4181-11e9-9891-4531fc425e17.png">

**Comment by redaranj** [comment]
@cstiens I think you must have a cached version of the stylesheet since none of the style changes I made are in the screenshot. Can you hold shift while clicking refresh in your browser?

**Comment by cstiens** [comment]
@redaranj Well that makes a world of difference! :) It looks perfect!!! Thank you Darren! Next time, I'll ask for your screenshot first. :)

**Comment by tiffrobo** [comment]
This looks great @redaranj! You are so fast :) 

- [ ] We need to update Josh Levy's avatar. I've attached the pngs here. 

![desktop-joshx1](https://user-images.githubusercontent.com/30634981/54040605-69097d80-418b-11e9-9917-d14c5d44874a.png)
![desktop-joshx2](https://user-images.githubusercontent.com/30634981/54040606-69097d80-418b-11e9-9683-4c22a7a93dfc.png)

Thanks!

**Comment by tiffrobo** [comment]
One more thing- Can we update the copy under Josh's bio from U.S. to US, please? We need to be consistent across the site with any US or UK abreviations. None should have U.S. or U.K. 
Thanks again!

**Comment by redaranj** [comment]
@tiffrobo The profile image updates and U.S. -> US fix are released.

**Comment by tiffrobo** [comment]
You rock @redaranj! Looks good!
