### ISSUE TITLE
Update Holly's bio

### ISSUE THREAD

**Issue by cstiens** [digiresilience/landing#2]
Here's Holly's updated bio:

Holly builds projects to address human rights and conflict issues. Before co-founding CDR she developed its first community iteration at Small Media. Holly also co-founded Security First, working on an app to make digital and physical security advice more accessible to human rights activists. She previously worked at Crisis Action where she launched and led the Emerging Powers program and also helped set up Videre where she framed the need for safer, more effective video documentation and helped to launch projects around the world.

**Comment by tinabeans** [comment]
Updated :)
